---
title: "Indianapolis DRHotNet Demo"
author: "Daniel P. Riggins"
date: "1/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Libraries, message=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
library(sf)
library(mapdeck)
library(maptools)
library(SpNetPrep)
library(spatstat)
```

```{r Download 2018 ARIES dataset}

download.file(
    url = "https://hub.mph.in.gov/dataset/4ac55064-1f0d-4e5e-aeee-12faf28d6175/resource/cc90589c-72d8-4d92-a5fe-73254b555c73/download/aries_crash_data_2018.csv",
    destfile = "raw_ARIES_2018.csv"
)

```

```{r Parsing specification}

# Tell the read_csv function how we want it to parse types for each column of the csv files. 
parse_spec <- cols(
    INDEXING_NUMBER = col_double(),
    INDIVIDUAL_MR_RECORD = col_double(),
    UNIT_MR_NUMBER = col_double(),
    STATUSCDE = col_character(),
    PERSONNMB = col_double(),
    PERSONTYPECDE = col_skip(),
    PERSONTYPEDESCR = col_character(),
    GENDERCDE = col_character(),
    AGE_GRP = col_character(),
    POSINVEHCDE = col_skip(),
    POSINVEHDESCR = col_character(),
    EJECTTRAPCDE = col_skip(),
    EJECTTRAPDESCR = col_character(),
    SAFETYEQUUSEDCDE = col_skip(),
    SAFETYEQUUSEDDESCR = col_character(),
    SAFETYEQUEFFIND = col_character(),
    INJSTATUSCDE = col_skip(),
    INJSTATUSDESCR = col_character(),
    INJNATURECDE = col_skip(),
    INJNATUREDESCR = col_character(),
    INJLOCCDE = col_skip(),
    INJLOCCDESCR = col_character(),
    TESTGIVENCDE = col_skip(),
    TESTGIVENDESCR = col_character(),
    RESULTALCHTXT = col_double(),
    RESULTDRUGIND = col_character(),
    AGENCYORITXT = col_skip(),
    AGENCYORIDESCR = col_character(),
    COUNTYCDE = col_skip(),
    COUNTY_STATE = col_skip(),
    COUNTYDESCR = col_character(),
    CITYCDE = col_skip(),
    CITYDESCR = col_character(),
    COLLDTE = col_character(),
    COLLISION_DAY = col_character(),
    COLLISION_MONTH = col_character(),
    COLLISION_YEAR = col_double(),
    COLLISION_TIME = col_character(),
    COLLISION_TIME_AM_PM = col_character(),
    MOTORVEHINVOLVEDNMB = col_double(),
    TRAILERSINVOLVEDNMB = col_double(),
    INJUREDNMB = col_double(),
    DEADNMB = col_double(),
    DEERNMB = col_double(),
    RDWYSUFFIXTXT = col_character(),
    RDWYRAMPTXT = col_character(),
    INTERINTERCHANGETXT = col_character(),
    INCORPLIMITIND = col_character(),
    PROPDAMAGECDE = col_skip(),
    PROPDAMAGEDESCR = col_character(),
    LATDECIMALNMB = col_double(),
    LONGDECIMALNMB = col_double(),
    TRAFFICCNTLOPIND = col_character(),
    AGGRESSIVEDRIVEIND = col_character(),
    HITRUNIND = col_character(),
    SCHOOLZONEIND = col_character(),
    RUMBLESTRIPIND = col_character(),
    CONSTRUCTIND = col_character(),
    LIGHTCONDCDE = col_skip(),
    LIGHTCONDDESCR = col_character(),
    WEATHERCDE = col_skip(),
    WEATHERDESCR = col_character(),
    SURFACETYPECDE_CONDDESCR = col_character(),
    SURFACETYPECDE = col_skip(),
    SURFACETYPEDESCR = col_character(),
    PRIMARYFACTORCDE = col_skip(),
    PRIMARYFACTORDESCR = col_character(),
    MANNERCOLLCDE = col_skip(),
    MANNERCOLLDESCR = col_character(),
    TIMENOTIFIEDTXT = col_character(),
    TIMENOTIFIEDAMPMTXT = col_character(),
    TIMEARRIVEDTXT = col_character(),
    TIMEARRIVEDAMPMTXT = col_character(),
    INVESTCOMPLETEIND = col_character(),
    PHOTOSTAKENIND = col_character(),
    UNIQUELOCATIONID = col_character(),
    STATEPROPIND = col_character(),
    TRAFFICCNTRLCDE = col_skip(),
    TRAFFICCNTRLDESCR = col_character(),
    UNITNMB = col_double(),
    UNIT_VEHICLE_NUMBER = col_double(),
    UNITTYPECDE = col_skip(),
    UNITTYPEDESCR = col_character(),
    VEHYEARTXT = col_double(),
    VEHMAKETXT = col_character(),
    VEHMODELTXT = col_character(),
    OCCUPSNMB = col_double(),
    VEHLICSTATECDE = col_character(),
    VEHLICSTATEDESCR = col_skip(),
    AXELSTXT = col_double(),
    SPEEDLIMITTXT = col_character(),
    TOWEDIND = col_character(),
    VEHUSECDE = col_skip(),
    VEHUSEDESCR = col_character(),
    ROADTYPECDE = col_skip(),
    ROADTYPEDESCR = col_character(),
    TRAVDIRCDE = col_character(),
    TRAVDIRDESCR = col_skip(),
    EMGERENCY_RUN = col_character(),
    FIREIND = col_character(),
    COLLEVENTCDE = col_skip(),
    COLLEVENTDESCR = col_character(),
    PRECOLLACTCDE = col_skip(),
    PRECOLLACTDESCR = col_character(),
    DISTRICT = col_character(),
    DISTRICT_NUM = col_skip(),
    SUBDISTRICT = col_character()
)

```

```{r Parse the raw data}

raw_ARIES <- readr::read_csv("raw_ARIES_2018.csv", col_types = parse_spec)

glimpse(raw_ARIES)
```

```{r Light wrangling}

# Standardize the date format
raw_ARIES$COLLDTE <- raw_ARIES$COLLDTE %>% 
    lubridate::ymd() %>% 
    as.character()

# Clean the table
ARIES <- raw_ARIES %>%
    # Delete duplicate rows
    distinct(
    ) %>%
    # Remove rows that don't have a valid latitude, longitude, and date
    filter(
        !is.na(LATDECIMALNMB) & 
        !is.na(LONGDECIMALNMB) &
        !is.na(COLLDTE) &
        LATDECIMALNMB != 0 & 
        LONGDECIMALNMB != 0
    ) %>%
    # Give a unique identifier to each row
    mutate(
        true_id = 1:n()
    )

glimpse(ARIES)
```

```{r Wrangling crash records}

ARIES %>%
    # Consolidate pedestrian-involvement variables
    mutate(
        ped_involved = if_else(
            PERSONTYPEDESCR %in% "Pedestrian" | COLLEVENTDESCR %in% "Pedestrian",
            TRUE,
            FALSE
        )
    ) %>%
    # Group by identifier for each crash event
    group_by(
        INDIVIDUAL_MR_RECORD
    ) %>%
    # Consolidate each group of individuals involved in a crash event into one record
    summarize(
        longitude = first(LONGDECIMALNMB),
        latitude = first(LATDECIMALNMB),
        date = first(COLLDTE),
        ped_involved = if_else(
            any(ped_involved == TRUE),
            TRUE,
            FALSE
        )
    ) %>%
    ungroup(
    ) %>%
    # Convert the format to simple feature collection--one of the standard formats for geographic analysis in R
    st_as_sf(
        coords = c("longitude","latitude"),
        crs = 4326
    ) -> crashes

glimpse(crashes)
```

```{r Subset to Marion County Crashes}
st_read("https://opendata.arcgis.com/datasets/4ff11b4054d84cb2ad3513f228624d2b_9.geojson") -> marion_boundary

st_intersects(crashes, marion_boundary, sparse = FALSE) -> in_marion

crashes %>% filter(in_marion == TRUE) -> marion_crashes

```

```{r Interactive Heatmap}
mapdeck::set_token("pk.eyJ1IjoiZGFucmlnZ2lucyIsImEiOiJVUjd1NnRJIn0.lqlMQwXYjt6R2heJOYo_sw")

base_map <- mapdeck(
    style = "mapbox://styles/mapbox/dark-v10",
    location = c(-86.15801704875246, 39.768569808746264),
    zoom = 10,
    pitch = 25
)

base_map %>%
    add_heatmap(
        data = (crashes %>% filter(ped_involved == TRUE)),
    )

```

```{r}
st_read("https://opendata.arcgis.com/datasets/fa9ec663cf25407a9b7645ff14334a7f_13.geojson") -> marion_streets

marion_streets %>%
  # Transform onto local Indiana map projection
  st_transform(crs = 7327) %>%
  # Convert to spatial format to enable conversion to...
  as_Spatial() %>% 
  # ...linear network format
  as.linnet() %>%
  # Break linear network into a list of its disconnected components
  connected(what = "components") -> street_components.linnet

# Select for only the largest, continuous component of the network
street_components.linnet[[1]] -> continuous_streets.linnet

```

```{r}
continuous_streets.linnet %>%
  # Simplify the number of redundant segments
  SpNetPrep::SimplifyLinearNetwork(Angle = 20, Length = 50) -> simplified_continuous_streets.linnet
```

```{r}
marion_crashes %>%
  # Transform to local Indiana map projection
  st_transform(7327) %>%
  # Convert to spatial format to enable conversion to...
  as_Spatial() %>%
  # Planar point pattern format
  as.ppp() -> marion_crashes.ppp

simplified_continuous_streets.linnet %>% 
  # Convert to complementary planar segment pattern
  as.psp.linnet() -> simplified_continuous_streets.psp

spatstat
  
```

